### ISSUE TITLE
App not compatible with Android 13

### ISSUE THREAD

**Issue by ShunitP** [georg-jung/technion-robotic-arm#17]
Devices with Android version 13 cannot download the app.
The error in the play store is regarding incompatibility.

@georg-jung do you have an idea why we aren't compatible?
Thanks!

**Comment by georg-jung** [comment]
I anwered some newly required questionnaires on Google Play to my best knowledge. I hope this helped. I'm currently on a Pixel 7 with Android 13 (Patch Level May '23) and was able to install without hassles from Google Play. Please check again and let me know.

**Comment by ShunitP** [comment]
Hi Georg,

Actually Uzi (cc) is the one that tried to install it but got
incompatibility msg.
He also has Pixel 7 with Android 13.

Can you please share which version you succeeded to install? Is this
version public or only for internal users?

Thanks
Shunit

**Comment by georg-jung** [comment]
I have 2.7.29 installed. It is the public version. I think this isn't related to the app's code itself but to the play store listing though. If I'm right that'd be independent of the version. Please try again and take a screenshot of the message if it still doesn't work.

**Comment by georg-jung** [comment]
Ah, and note that CC doesn't work with GitHub issues as it does with other emails - there isn't a way for me to contact Uzi at this point.

**Comment by ShvadronUzi** [comment]
Hi, strange, but after reading the above I tried to access again the provided link to play store and now it let me install it without a problem.... Yesterday the same link ( I verified) stated that my pixel 7 is not compatible (I shared a screenshot with Shunit).
This issue may be closed at this time

**Comment by georg-jung** [comment]
Okay, great!

I think this makes sense though, see above:

> I anwered some newly required questionnaires on Google Play to my best knowledge. I hope this helped.

>  I think this isn't related to the app's code itself but to the play store listing though.

There were some new legal requirements. It was required to fill in some forms to make the app installable on Android 13+. Probably the ones related to advertisment ids and privacy made the relevant difference.
