### ISSUE TITLE
Validate Configuration Values on Write

### ISSUE THREAD

**Issue by ShunitP** [georg-jung/technion-robotic-arm#5]
There are several parameters that have invalid values, that the app should block the user from entering them and alert the user these values are invalid with a short explanation.
Even though, the hand controller already checked for invalid values and changes them automatically to valid according to specific logic, it is better to inform the user about it on the app.

Some examples of invalid values - 
preset mode: more than 12 presets, more than 10 movements per preset.
configuration mode: filter window must be between 1 to 20, and more.

The full table of invalid/valid parameters will be updated here soon.

ToDo:
* [ ] Define what values are valid for which field
* [ ] Implement validation in the app in an abstract way
  * Probably involves a new interface around [ConfigurationService.kt](https://github.com/Haifa3D/haifa3d-hand-app/blob/master/src/android/Haifa3d/app/src/main/java/com/gjung/haifa3d/ble/ConfigurationService.kt) and new code on the ui side that makes use of it.
* [ ] Add values from above definition to the app's concrete config value definition

**Comment by georg-jung** [comment]
Note that the number of presets is already fixed to 12. The other points are applicable though. As validation of config values and limiting the number of movements per preset is technically something different, I'll open a second issue to keep track of the development.

**Comment by ShunitP** [comment]
Hi,
Here is the full table contains each configuration parameter and its valid values:
you are welcome to comment on that if you think some values should be different.

| # | Name | type | value type | min value | max value | value unit | value   explanation |
| -- | -- | -- | -- | -- | -- | -- | -- |
| 1 | Low Torque Value | basic | integer | 0 | 255 | VALUE UNIT (see 12) | in practice: value  = x    VALUE UNIT. High value results high hand torque |
| 2 | High Torque Value | basic | integer | 0 | 255 | VALUE UNIT (see 12) | in practice:   value  = x  VALUE UNIT. High value results high hand   torque |
| 3 | Torque Measure Start | advanced | integer | 0 | 255 | [msec] | ignore high current   during the first x[msec] |
| 4 | Window Width Filter | advanced | integer | 1 | 20 | [samples] | #of sample for moving   average filter |
| 5 | Low Torque Slope Value | basic | integer | 0 | 255 | [msec] | the time period when   the current value increasing. High value | results high hand torque |
| 6 | High Torque Slope Value | basic | integer | 0 | 255 | [msec] | the time period when   the current value increasing. High value results high hand torque |
| 7 | Threshold Factor Motor0 | advanced | integer | 0 | 255 | [%] | the percentage of   thrshold values which are applied on motor 0. motor0_value_thr = value_thr *   factor% (same for the slope_thr) |
| 8 | Threshold Factor Motor1 | advanced | integer | 0 | 255 | [%] | the percentage of   thrshold values which are applied on motor 1. motor1_value_thr = value_thr *   factor% (same for the slope_thr) |
| 9 | Threshold Factor Motor2 | advanced | integer | 0 | 255 | [%] | the percentage of   thrshold values which are applied on motor 2. motor2_value_thr = value_thr *   factor% (same for the slope_thr) |
| 10 | Threshold Factor Motor3 | advanced | integer | 0 | 255 | [%] | the percentage of   thrshold values which are applied on motor 3. motor3_value_thr = value_thr *   factor% (same for the slope_thr) |
| 11 | Threshold Factor Motor4 | advanced | integer | 0 | 255 | [%] | the percentage of   thrshold values which are applied on motor 4. motor4_value_thr = value_thr *   factor% (same for the slope_thr) |
| 12 | Threshold Value Unit | advance/more | integer | 1 | 255 | [.] | VALUE UNIT |
| 13 | reset presets | basic | - | - | - | - | - |
| 14 | reset configuration | basic | - | - | - | - | - |
| 15 | debugging | advanced | - | - | - | - | - |
