### ISSUE TITLE
Configuration Mode Enhancement

### ISSUE THREAD

**Issue by ShunitP** [georg-jung/technion-robotic-arm#6]
The visualization and UX of the configuration mode should be enhanced, such as:
* Split it to basic and expert
* add explanation/help for each parameter.
* more user-friendly
* other ideas

**Comment by asafazar92** [comment]
Hey @ShunitP , we would like to get a clarification . we are are not sure what you meant by "split it to basic/expert". currently there are 4 categories, can you please be specific which category goes under "basic" and which under "expert"?

**Comment by ShunitP** [comment]
Hi @asafazar92 
I'm not sure which categories you meant but, here is my idea:
If we split the configuration to basic (the main screen), advanced (second screen) and maybe add a "more" (third screen) - 
(see **type column**) 


| # | Name | type | value type | min value | max value | value unit | value   explanation |
| -- | -- | -- | -- | -- | -- | -- | -- |
| 1 | Low Torque Value | basic | integer | 0 | 255 | VALUE UNIT (see 12) | in practice: value  = x    VALUE UNIT. High value results high hand torque |
| 2 | High Torque Value | basic | integer | 0 | 255 | VALUE UNIT (see 12) | in practice:   value  = x  VALUE UNIT. High value results high hand   torque |
| 3 | Torque Measure Start | advanced | integer | 0 | 255 | [msec] | ignore high current   during the first x[msec] |
| 4 | Window Width Filter | advanced | integer | 1 | 20 | [samples] | #of sample for moving   average filter |
| 5 | Low Torque Slope Value | basic | integer | 0 | 255 | [msec] | the time period when   the current value increasing. High value | results high hand torque |
| 6 | High Torque Slope Value | basic | integer | 0 | 255 | [msec] | the time period when   the current value increasing. High value results high hand torque |
| 7 | Threshold Factor Motor0 | advanced | integer | 0 | 255 | [%] | the percentage of   thrshold values which are applied on motor 0. motor0_value_thr = value_thr *   factor% (same for the slope_thr) |
| 8 | Threshold Factor Motor1 | advanced | integer | 0 | 255 | [%] | the percentage of   thrshold values which are applied on motor 1. motor1_value_thr = value_thr *   factor% (same for the slope_thr) |
| 9 | Threshold Factor Motor2 | advanced | integer | 0 | 255 | [%] | the percentage of   thrshold values which are applied on motor 2. motor2_value_thr = value_thr *   factor% (same for the slope_thr) |
| 10 | Threshold Factor Motor3 | advanced | integer | 0 | 255 | [%] | the percentage of   thrshold values which are applied on motor 3. motor3_value_thr = value_thr *   factor% (same for the slope_thr) |
| 11 | Threshold Factor Motor4 | advanced | integer | 0 | 255 | [%] | the percentage of   thrshold values which are applied on motor 4. motor4_value_thr = value_thr *   factor% (same for the slope_thr) |
| 12 | Threshold Value Unit | advance/more | integer | 1 | 255 | [.] | VALUE UNIT |
| 13 | reset presets | basic | - | - | - | - | - |
| 14 | reset configuration | basic | - | - | - | - | - |
| 15 | debugging | advanced | - | - | - | - | - |

I'm not sure if the "third screen" is necessary (the "more" option), so do whatever you think is best

**Comment by mikimn** [comment]
Not sure there's a reason to split this into screens. Why not just remain with one screen, containing headers for each section? Something like:

<pre>
Basic Configuration
----------------------
  ~~~Option 1~~~
  ~~~Option 2~~~
          .
          .

Advanced Configuration
----------------------
  ~~~Option 1~~~
  ~~~Option 2~~~
          .
          .

More Options
----------------------
  ~~~Option 1~~~
  ~~~Option 2~~~
          .
          .
</pre>

**Comment by ShunitP** [comment]
Sounds good, maybe it can be expand and collapse sections for better UX... Whatever you think is best to keep-it-simple for the common users.

**Comment by mikimn** [comment]
We can probably stick to the basic design for now. Simple users will stay at the top of the page (Basic Configuration) because they find what they need, while advanced users will probably actively look for the advanced features

**Comment by mikimn** [comment]
@asafazar92 @leviniv See how I tagged the issue with `help wanted`. For further issues, if you need extra attention for the issue, add this label. Also, if you got all the information you meed, remove the label.
