### ISSUE TITLE
[UI/UX] Menu looks broken on phones with front camera punch hole

### ISSUE THREAD

**Issue by georg-jung** [georg-jung/technion-robotic-arm#8]
Newer phones that have a punch hole for their front camera do have a much bigger notification bar. The app's main menu does not seem to be compatible with this: (see below, Google Pixel 5)

Note that this is just a visual thing and does not have any functional effects.

![image](https://user-images.githubusercontent.com/5229609/98801235-d6b28600-2411-11eb-999b-1687b309f3f5.png)

**Comment by mikimn** [comment]
This issue should probably be closed as a consequence of #9
