### ISSUE TITLE
Move navigation drawer items to bottom navigation

### ISSUE THREAD

**Issue by mikimn** [georg-jung/technion-robotic-arm#9]
As a user, I want 1-click access to my presets and live mode, so that I don't have to open the navigation drawer every time to navigate through screens.

As a consequence, the navigation drawer should probably be removed and the main screen should contain a bottom navigation bar with 4 items:
* Home
* Live Control
* Presets
* Configuration

The "About" section and "Disconnect" button should move to an overflow menu at the app bar since it's a navigation item of secondary importance.

@georg-jung Thoughts?

**Comment by georg-jung** [comment]
Seems sensible. Just one thought: we have the disconnect button there too and that needs to find a new place then too. Maybe the overflow menu is fine for this too as I guess - for users, not developers - it's a rather seldomly used thing.

**Comment by mikimn** [comment]
Yeah,  I will add that to the original description
